FROM golang:1.25.3-alpine

WORKDIR /app

RUN go install github.com/githubnemo/CompileDaemon@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 420

CMD CompileDaemon -command="./app" -build="go build -o app ./cmd/app"
